name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Create .env file in backend
        run: |
          echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" > backend/.env
    
      - name: Create service account key in backend
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > backend/serviceAccountKey.json

      - name: Install dependencies (root + workspaces)
        run: npm install
        
      - name: Build frontend
        run: npm run build -w front-end
        
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT}}
          channelId: live
          projectId: papakjai-eda88
